version: '3'

services:
  db:
    image: mariadb:10.3
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'task_db'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - database1_network

  djangoapp:
    build: ./backend
    volumes: 
      - ./backend:/app/backend
    depends_on: 
      - db
    networks:
      - database1_network
      - nginx_network
      - cache_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/local.conf:/etc/nginx/conf.d/default.conf 
      - ./nginx/404.html:/usr/share/nginx/html/404.html
      - ./nginx/images:/app/frontend/images
      - ./frontend/build:/app/frontend
    networks:
      - nginx_network
  
  # frontend:
  #   tty: true
  #   build: ./frontend
  #   command: npm start
  #   volumes:
  #     - ./frontend:/app/frontend
  #     - ./frontend/node_modules:/app/frontend/node_modules
  #   ports:
  #     - "3000:3000"

  redis:
    image: redis
    ports:
      - "6379:6379"
    depends_on:
      - djangoapp
    networks:
      - cache_network

networks:
  nginx_network:
    driver: bridge
  database1_network:
    driver: bridge
  cache_network:
    driver: bridge